name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  test:

    strategy:
      matrix:
        node-version: [ 18.x ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test
  